name: 分享经验
description: 分享某个方向的经验分享。
title: "[Share]: "
labels: ["share"]
assignees:
  - syy11cn
body:
  - type: dropdown
    id: category
    attributes:
      label: 经验分类
      description: 请选择你所要分享经验的类别
      options:
        - 不确定
        - 入学
        - 学生活动
        - 上课 / 选课
        - 考试
        - 竞赛
        - 实习
        - 实验室
        - 活水
        - 毕业工作
        - 国内深造
        - 国外深造
    validations:
      required: true
  - type: markdown
    id: description
    attributes:
      label: 经验描述
      description: 请简单描述你想要分享的经验，或探讨你的经验应该归入哪个类别。
    validations:
      required: true
  - type: checkboxes
    id: term
    attrbutes:
      label: 说明
      description: 提交 issue 请勾选本说明。
      options:
        - label: 我的经验分享中不包含违法或政治敏感内容。
          required: true
