name: 建议 & 反馈
description: 如果你对某篇文章的内容持有不同意见，或对本项目的发展有更好的建议，欢迎指出。
title: "[feedback]: "
labels: ["feedback"]
assignees:
  - syy11cn
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议 & 反馈。
  - type: textarea
    id: feedback
    attributes:
      label: 反馈内容
      description: 请填写你的反馈内容。
    validations:
      required: true

# 建议 & 反馈
